export const CREATE_NOTE_PENDING = 'note/CREATE_NOTE_PENDING';
export const CREATE_NOTE_SUCCESS = 'note/CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_FAILED = 'note/CREATE_NOTE_FAILED';

export const UPDATE_NOTE_PENDING = 'note/UPDATE_NOTE_PENDING';
export const UPDATE_NOTE_SUCCESS = 'note/UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAILED = 'note/UPDATE_NOTE_FAILED';

export const DELETE_NOTE_PENDING = 'note/DELETE_NOTE_PENDING';
export const DELETE_NOTE_SUCCESS = 'note/DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAILED = 'note/DELETE_NOTE_FAILED';
