export const SET_USER_TOKEN = 'auth/SET_USER_TOKEN';
export const SET_BRANCH = 'auth/SET_BRANCH';

export const LOGIN_PENDING = 'auth/LOGIN_PENDING';
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'auth/LOGIN_FAILED';

export const CHANGE_PASSWORD_PENDING = 'auth/CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD_SUCCESS = 'auth/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'auth/CHANGE_PASSWORD_FAILED';

export const GET_BRANCHES_PENDING = 'auth/GET_BRANCHES_PENDING';
export const GET_BRANCHES_SUCCESS = 'auth/GET_BRANCHES_SUCCESS';
export const GET_BRANCHES_FAILED = 'auth/GET_BRANCHES_FAILED';
