export const RESET = 'scan/RESET';

export const SET_LOCATION = 'scan/SET_LOCATION';

export const VERIFICATION_PENDING = 'scan/VERIFICATION_PENDING';
export const VERIFICATION_SUCCESS = 'scan/VERIFICATION_SUCCESS';
export const VERIFICATION_FAILED = 'scan/VERIFICATION_FAILED';

export const GET_PRODUCT_DETAIL_PENDING = 'scan/GET_PRODUCT_DETAIL_PENDING';
export const GET_PRODUCT_DETAIL_SUCCESS = 'scan/GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILED = 'scan/GET_PRODUCT_DETAIL_FAILED';
