export const RESET = 'verification/RESET';

export const GET_VERIFICATION_LIST_PENDING =
  'verification/GET_VERIFICATION_LIST_PENDING';
export const GET_VERIFICATION_LIST_SUCCESS =
  'verification/GET_VERIFICATION_LIST_SUCCESS';
export const GET_VERIFICATION_LIST_FAILED =
  'verification/GET_VERIFICATION_LIST_FAILED';

export const CHECK_VERIFICATION_PENDING =
  'verification/CHECK_VERIFICATION_PENDING';
export const CHECK_VERIFICATION_SUCCESS =
  'verification/CHECK_VERIFICATION_SUCCESS';
export const CHECK_VERIFICATION_FAILED =
  'verification/CHECK_VERIFICATION_FAILED';

export const VERIFICATION_PENDING = 'verification/VERIFICATION_PENDING';
export const VERIFICATION_SUCCESS = 'verification/VERIFICATION_SUCCESS';
export const VERIFICATION_FAILED = 'verification/VERIFICATION_FAILED';
