export const RESET = 'verification/RESET';

export const GET_VERIFICATION_LIST_PENDING =
  'verification/GET_VERIFICATION_LIST_PENDING';
export const GET_VERIFICATION_LIST_SUCCESS =
  'verification/GET_VERIFICATION_LIST_SUCCESS';
export const GET_VERIFICATION_LIST_FAILED =
  'verification/GET_VERIFICATION_LIST_FAILED';
