export const RESET = 'identification/RESET';

export const GET_PRODUCT_DETAIL_PENDING =
  'identification/GET_PRODUCT_DETAIL_PENDING';
export const GET_PRODUCT_DETAIL_SUCCESS =
  'identification/GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILED =
  'identification/GET_PRODUCT_DETAIL_FAILED';

export const GET_PRODUCT_IDENTIFICATION_PENDING =
  'identification/GET_PRODUCT_IDENTIFICATION_PENDING';
export const GET_PRODUCT_IDENTIFICATION_SUCCESS =
  'identification/GET_PRODUCT_IDENTIFICATION_SUCCESS';
export const GET_PRODUCT_IDENTIFICATION_FAILED =
  'identification/GET_PRODUCT_IDENTIFICATION_FAILED';
