export const SET_START_TIME = 'count/SET_START_TIME';
export const SET_END_TIME = 'count/SET_END_TIME';
export const RESET = 'count/RESET';

export const SET_LOCATION = 'count/SET_LOCATION';

export const VERIFICATION_PENDING = 'count/VERIFICATION_PENDING';
export const VERIFICATION_SUCCESS = 'count/VERIFICATION_SUCCESS';
export const VERIFICATION_FAILED = 'count/VERIFICATION_FAILED';

export const SUBMIT_COUNT_PENDING = 'count/SUBMIT_COUNT_PENDING';
export const SUBMIT_COUNT_SUCCESS = 'count/SUBMIT_COUNT_SUCCESS';
export const SUBMIT_COUNT_FAILED = 'count/SUBMIT_COUNT_FAILED';
