export const RESET = 'scan/RESET';

export const GET_LOCATION_LIST_PENDING = 'scan/GET_LOCATION_LIST_PENDING';
export const GET_LOCATION_LIST_SUCCESS = 'scan/GET_LOCATION_LIST_SUCCESS';
export const GET_LOCATION_LIST_FAILED = 'scan/GET_LOCATION_LIST_FAILED';
