export const RESET = 'location/RESET';

export const GET_LOCATION_LIST_PENDING = 'location/GET_LOCATION_LIST_PENDING';
export const GET_LOCATION_LIST_SUCCESS = 'location/GET_LOCATION_LIST_SUCCESS';
export const GET_LOCATION_LIST_FAILED = 'location/GET_LOCATION_LIST_FAILED';

export const GET_LOCATION_DETAILS_PENDING =
  'location/GET_LOCATION_DETAILS_PENDING';
export const GET_LOCATION_DETAILS_SUCCESS =
  'location/GET_LOCATION_DETAILS_SUCCESS';
export const GET_LOCATION_DETAILS_FAILED =
  'location/GET_LOCATION_DETAILS_FAILED';

export const UPDATE_ITEM_QTY_PENDING = 'location/UPDATE_ITEM_QTY_PENDING';
export const UPDATE_ITEM_QTY_SUCCESS = 'location/UPDATE_ITEM_QTY_SUCCESS';
export const UPDATE_ITEM_QTY_FAILED = 'location/UPDATE_ITEM_QTY_FAILED';
