export const SET_PROFILE = 'account/SET_PROFILE';

export const PROFILE_PENDING = 'account/PROFILE_PENDING';
export const PROFILE_SUCCESS = 'account/PROFILE_SUCCESS';
export const PROFILE_FAILED = 'account/PROFILE_FAILED';

export const CHANGE_PASSWORD_PENDING = 'account/CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD_SUCCESS = 'account/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'account/CHANGE_PASSWORD_FAILED';

export const UPDATE_PROFILE_PENDING = 'account/UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'account/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'account/UPDATE_PROFILE_FAILED';
