export const RESET = 'bluetooth/RESET';

export const SET_BLUETOOTH_CONNECT_LOADING =
  'bluetooth/SET_BLUETOOTH_CONNECT_LOADING';

export const SET_BLUETOOTH_CONNECTION_LOADING =
  'bluetooth/SET_BLUETOOTH_CONNECTION_LOADING';

export const SET_BLUETOOTH_ENABLED = 'bluetooth/SET_BLUETOOTH_ENABLED';
export const SET_BLUETOOTH_DISABLED = 'bluetooth/SET_BLUETOOTH_DISABLED';

export const SET_BLUETOOTH_SEACRH_LOADING =
  'bluetooth/SET_BLUETOOTH_SEACRH_LOADING';

export const SET_BLUETOOTH_PAIRED = 'bluetooth/SET_BLUETOOTH_PAIRED';
export const SET_BLUETOOTH_ALREADY_PAIRED_LIST =
  'bluetooth/SET_BLUETOOTH_ALREADY_PAIRED_LIST';
export const SET_BLUETOOTH_FOUNDED_LIST =
  'bluetooth/SET_BLUETOOTH_FOUNDED_LIST';
